import os
stat = os.system("mkdir -p prediction_service/model")
stat = os.system("mkdir webapp")
stat = os.system("touch app.py ")
stat = os.system("touch prediction_service/__init__.py")
stat = os.system("touch prediction_service/prediction.py")
stat = os.system("mkdir -p webapp/stastic/css")
stat = os.system("mkdir -p webapp/stastic/script")
stat = os.system("touch webapp/stastic/css/main.css")
stat = os.system("touch webapp/stastic/script/index.js")
stat = os.system("mkdir webapp/templates")
stat = os.system("touch webapp/templates/index.html")
stat = os.system("touch webapp/templates/404.html")
stat = os.system("touch webapp/templates/base.html")
