base:
  project: winequality-project
  random_state: 42
  target_col: quality

data_source:
  s3_source: /home/shubham/MLOPSday2/simple_app/data_given/winequality.csv

load_data:
  raw_dataset_csv: /home/shubham/MLOPSday2/simple_app/data/raw/winequality.csv

split_data:
  train_path: /home/shubham/MLOPSday2/simple_app/data/processed/train_winequality.csv
  test_path: /home/shubham/MLOPSday2/simple_app/data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
        # alpha: 0.88
        # l1_ratio: 0.89
        # alpha: 0.9
        # l1_ratio: 0.4
        alpha: 0.7
        l1_ratio: 0.6
model_dir: /home/shubham/MLOPSday2/simple_app/saved_models

reports:
  params: /home/shubham/MLOPSday2/simple_app/report/params.json
  scores: /home/shubham/MLOPSday2/simple_app/report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNetRegression1
  run_name: mlops
  registered_model_name: ElasticNetWineModelShubham
  remote_server_uri: http://0.0.0.0:5000